apiVersion: 1

datasources:
  - name: Zabbix
    type: alexanderzobnin-zabbix-datasource
    access: proxy
    url: http://zabbix-web:8080
    jsonData:
      username: Admin
      trends: true
      trendsFrom: "7d"
      trendsRange: "7d"
      cacheTTL: "1m"
    secureJsonData:
      password: zabbix
    editable: true


